[theme]
primaryColor = "#5e72e4"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[server]
maxUploadSize = 200
enableCORS = false
enableXsrfProtection = true
# 禁用文件监控以避免inotify问题
fileWatcherType = "none"

[browser]
gatherUsageStats = false
serverAddress = "0.0.0.0"

[runner]
fastReruns = false
